package buildSrc

object Versions {

    const val google_services_version = "4.3.3"
    const val hilt_version = "2.28-alpha"
    const val hilt_jetpack_version = "1.0.0-alpha01"
    const val androidx_version = "1.1.0"
    const val androidx_core_version = "1.3.0"
    const val androidx_lifecycle = "2.2.0"
    const val gradle_version = "3.5.1"
    const val kotlin_version = "1.3.72"
    const val retrofit_version = "2.7.0"
    const val moshi_converter_version = "2.4.0"
    const val okHttp_version = "3.11.0"
    const val coroutines_version = "1.3.7"
    const val room_version = "2.2.5"
    const val junit_version = "4.13"
    const val mockk_version = "1.9.3"
    const val dagger_version = "2.28"
    const val espresso_version = "3.2.0"
    const val junit_test_version = "1.1.1"
    const val navigation_version = "2.3.0"
    const val lottie_version = "3.4.0"
    const val glide_version = "4.11.0"
    const val palette_version = "1.0.0"
    const val robolectric_version = "4.3.1"
    const val fragment_test_version = "1.2.5"
    const val fragment_version = "1.2.5"
    const val firebase_config_ktx_version = "19.2.0"
    const val firebase_analytics_ktx_version = "17.4.4"

    // AndroidX
    const val androidx_appcompat_version = "1.0.2"
    const val androidx_cardview_version = "1.0.0"
    const val androidx_constraintlayout_version = "1.1.3"
    const val androidx_legacy_version = "1.0.0"
    const val androidx_multidex_version = "2.0.1"
    const val androidx_recyclerview_version = "1.0.0"
    const val androidx_transition_version = "1.0.0"
    const val androidx_core_testing = "2.1.0"
}